### ISSUE TITLE
Enable v4 PR / Push GitHub action

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#650]
### Dependencies
- #645
- #646 
- #647 
- #648 
- #649

# v0.4 Setup Infrastructure

This ticket adds a GitHub action that ensures that all tests pass and linting rules are satisfied whenever a PR or Push is made against the development-0.4 branch.

# Dependencies
- #645
- #646 
- #647 
- #648 
- #649

# Instructions
- [ ] Review the sample code below
- [ ] Add a file with that code (or similar) to the /.github/workflows` folder.  (The name of the file will be what is displayed during PRs.)
- [ ] Run the workflow manually ([link](https://github.com/hackforla/VRMS/actions)) to confirm that the action runs as expected and passes.
- [ ] Create a PR with one failing test and one failing lint rule.  Confirm that the action calls out the errors as expected.

# Acceptance Criteria
The created PR is rejected as expected, and modifying the PR by correcting the errors causes the action to accept the changes.

# Reference
```
name: PR Checks
on:
  push:
    branches: [development-0.4]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [development-0.4]
    paths-ignore:
      - "*.md"

jobs:
  test-backend-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          envkey_REACT_APP_PROXY: ${{ secrets.REACT_APP_PROXY }}
          file_name: backend/.env
      - name: Build the backend container
        run: docker-compose build backend
      - name: Run backend unit test suite
        run: docker-compose run --rm backend yarn run test --testPathIgnorePatterns=routers
      - name: Run backend code inspection
        run: docker-compose run --rm client yarn run lint

  test-client-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the client container
        run: docker-compose build client
      - name: Run client unit test suite
        run: docker-compose run --rm client yarn run test
      - name: Run client code inspection
        run: docker-compose run --rm client yarn run lint
```
